language: java
jdk:
  - oraclejdk8
addons:
    postgresql: "9.5"
sudo: false
before_script:
  - psql -c "CREATE DATABASE hello_back_end;"  postgres
  - psql -c "CREATE USER user WITH PASSWORD '11111';" postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE hello-back-end TO user;" -U postgres
branches:
  only:
    - master
script: mvn clean verify